export enum IdentityDocumentType {
    IDENTITY_DOCUMENT = 'INFRINGEMENT.FORM.IDENTITY_DOCUMENT_TYPE',
    REGISTRATION_PLATE = 'INFRINGEMENT.FORM.PLATE_TYPE',
    RUC = 'INFRINGEMENT.FORM.RUC_TYPE',
    REFUGEE_CARD = 'INFRINGEMENT.FORM.REFUGEE_TYPE',
    PASSPORT = 'INFRINGEMENT.FORM.PASSPORT_TYPE',
}

export const identityDocumentTypes = Object.values(IdentityDocumentType);