name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: All things angular
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.4.0
      with:
        working-directory: ./desarrollo
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        build_configuration: production
        base_href: /AMT-Redisenio-Usabilidad-Accesibilidad/
        deploy_branch: gh-pages
        angular_dist_build_folder: dist/infracciones-amt

permissions:
  contents: write
